using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Mvc;

using TravelInsuranceManagementSystem.Repo.Models;

using TravelInsuranceManagementSystem.Services.Interfaces;

namespace TravelInsuranceManagementSystem.Application.Controllers

{

    [Authorize(Roles = "Admin")]

    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]

    public class AdminController : Controller

    {

        private readonly IAdminService _adminService;

        private readonly SignInManager<User> _signInManager;// Manages login (password check, cookies)

        private readonly UserManager<User> _userManager;// Manages user data (create, delete, find)

        private readonly IAccountService _accountService;

        public AdminController(

            IAdminService adminService,

            SignInManager<User> signInManager,

            UserManager<User> userManager,

            IAccountService accountService)

        {

            _adminService = adminService;

            _signInManager = signInManager;

            _userManager = userManager;

            _accountService = accountService;

        }

        // --- DASHBOARD & REPORTS ---

        public async Task<IActionResult> Dashboard()

        {

            ViewData["Title"] = "Admin Dashboard";

            var summary = await _adminService.GetDashboardSummaryAsync();

            return View(summary);

        }

        public async Task<IActionResult> Policies()

        {

            ViewData["Title"] = "Policy Management";

            var policies = await _adminService.GetPolicyManagementDataAsync();

            return View(policies);

        }

        public async Task<IActionResult> Payments()

        {

            ViewData["Title"] = "Payment History";

            var payments = await _adminService.GetPaymentHistoryAsync();

            return View(payments);

        }

        public async Task<IActionResult> Claims()

        {

            ViewData["Title"] = "Claims Overview";

            var claimsData = await _adminService.GetClaimsOverviewAsync();

            return View(claimsData);

        }

        // --- AGENT MANAGEMENT ---

        [HttpGet]

        public async Task<IActionResult> Agents()

        {

            ViewData["Title"] = "Manage Agents";

            // Use AdminService to get agents with their workload stats (Policies, Claims, etc.)

            var agents = await _adminService.GetAgentsWithWorkloadAsync();

            return View(agents);

        }

        [HttpPost]

        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteAgent(int id)

        {

            // Use AdminService to delete the agent

            var success = await _adminService.DeleteAgentAsync(id);

            if (success)

            {

                TempData["Success"] = "Agent deleted successfully.";

            }

            else

            {

                TempData["Error"] = "Failed to delete agent. User not found.";

            }

            return RedirectToAction("Agents");

        }

        [HttpGet]

        public IActionResult CreateAgent()

        {

            ViewData["Title"] = "Register New Agent";

            return View();

        }

        [HttpPost]

        [ValidateAntiForgeryToken]

        public async Task<IActionResult> CreateAgent(User model, string Password)

        {


            ModelState.Remove("Password");       // Passed as parameter, not in model

            ModelState.Remove("ConfirmPassword"); // Not required for Admin creation

            ModelState.Remove("Id");             // Generated by DB

            ModelState.Remove("UserName");       // Generated from Email

            if (ModelState.IsValid)

            {

                // Basic check for empty password

                if (string.IsNullOrEmpty(Password))

                {

                    ModelState.AddModelError("", "Password is required.");

                    return View(model);

                }

                // Use AccountService to create user and assign "Agent" role securely

                var result = await _accountService.CreateAgent(model, Password);

                if (result.Succeeded)

                {

                    TempData["Success"] = "Agent registered successfully.";

                    return RedirectToAction("Agents");

                }

                // Display Identity errors (e.g., Duplicate Email, Weak Password)

                foreach (var error in result.Errors)

                {

                    ModelState.AddModelError("", error.Description);

                }

            }

            // If we got here, something failed, redisplay form

            return View(model);

        }

        // --- AUTHENTICATION ---

        [HttpPost]

        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Logout()

        {

            await _signInManager.SignOutAsync();

            HttpContext.Session.Clear();

            return RedirectToAction("SignIn", "Account");

        }

    }

}
